spring:
  application:
    name: ticketflow

  profiles:
    default: dev

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  mvc:
    format:
      date: iso
      date-time: iso

app:
  ticket:
    auto-close-after-days: 4
    auto-close-check-delay-hours: 24
  sla:
    check-delay-ms: 60000
